DESCRIBE t_sip_depto;
INSERT INTO T_SIP_DEPTO (CD_DEPTO,NM_DEPTO,SG_DEPTO)
VALUES (1, 'FINANCEIRO', 'FIN');

INSERT INTO T_SIP_DEPTO (CD_DEPTO,NM_DEPTO,SG_DEPTO)
VALUES (2, 'TI', 'TI');

COMMIT;

DESC T_SIP_PROJETO;

ALTER TABLE T_SIP_PROJETO RENAME COLUMN DT_INCIIO TO DT_INICIO;
DESC T_SIP_PROJETO;

INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (1, 'FIAP-1TDSPO', '10-SEP-24', '12-SEP-24');

SELECT * FROM T_SIP_PROJETO;

INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (2, 'FIAP-1TDSPO-2', TO_DATE ('10-09-2022', 'DD-MM-YYYY'), 
TO_DATE ('05-06-2024', 'DD-MM-YYYY'));

INSERT INTO T_SIP_PROJETO VALUES (3, 'FIAP 3', TO_DATE('05-09-2023', 'DD-MM-YYYY'), NULL);

INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO)
VALUES (6, 'FIAP-1TDSPO-3', TO_DATE ('10-09-2022', 'DD-MM-YYYY'));

SELECT CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO
    FROM T_SIP_PROJETO
    WHERE DT_TERMINO IS NULL;
    
--EX01
CREATE TABLE T_COPY_SIP_PROJETO AS
SELECT * FROM T_SIP_PROJETO WHERE 1=2;


INSERT INTO T_COPY_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
    (SELECT CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO
    FROM T_SIP_PROJETO
    WHERE DT_TERMINO IS NULL);
    
SELECT * FROM T_COPY_SIP_PROJETO;

UPDATE T_SIP_PROJETO SET DT_TERMINO = TO_DATE('10/09/2024', 'DD/MM/YYYY')
WHERE CD_PROJETO = 3;

SELECT * FROM T_SIP_PROJETO;

UPDATE T_SIP_PROJETO SET DT_TERMINO = (SELECT DT_TERMINO
                                        FROM T_SIP_PROJETO
                                        WHERE CD_PROJETO = 2);
SELECT * FROM T_SIP_PROJETO;

UPDATE T_SIP_PROJETO SET DT_TERMINO = NULL
WHERE CD_PROJETO > 2;

SELECT * FROM T_SIP_PROJETO;

DELETE FROM T_SIP_PROJETO;

SELECT * FROM T_SIP_PROJETO;

ROLLBACK;

SELECT * FROM T_SIP_PROJETO;

DELETE FROM T_SIP_PROJETO WHERE DT_TERMINO IS NULL;

SELECT * FROM T_SIP_PROJETO;

DELETE FROM T_SIP_DEPTO WHERE NM_DEPTO = 'TI';

COMMIT;
SELECT * FROM T_SIP_DEPTO;