-- Utilizando o Join para pegar a intersecção de Funcionário com Dependente
SELECT F.NM_FUNCIONARIO, D.NM_DEPENDENTE 
    FROM T_SIP_FUNCIONARIO F
    INNER JOIN T_SIP_DEPENDENTE D
    ON (F.CD_FUNC = D.CD_FUNC);
    
-- Join com departamento e funcionário
SELECT D.NM_DEPTO, F.NM_FUNCIONARIO
    FROM T_SIP_DEPTO D
    INNER JOIN T_SIP_FUNCIONARIO F
    USING (CD_DEPTO);
    
-- Join com tabelas associativas
SELECT F.CD_FUNC CODIGO_FUNC,
       F.NM_FUNCIONARIO NOME_FUNC,
       F.DT_ADMISSAO DATA_ADMISSAO,
       P.NM_PROJETO NOME_PROJETO,
       P.DT_INICIO DATA_INICIO_PROJETO,
       E.DS_PAPEL_FUNC_PROJ PAPEL_FUNC_PROJETO,
       E.DT_ENTRADA DATA_ENTRADA_FUNC_PROJETO,
       E.DT_SAIDA DATA_SAIDA_FUNC_PROJETO
FROM   T_SIP_FUNCIONARIO F INNER JOIN T_SIP_EXECUCAO_PROJ E
ON     (F.CD_FUNC = E.CD_FUNC) INNER JOIN T_SIP_PROJETO P
ON     (E.CD_PROJETO = P.CD_PROJETO)
ORDER BY F.NM_FUNCIONARIO;

--
SELECT F.CD_FUNC,
       F.NM_FUNCIONARIO,
       F.DS_ESTADO_CIVIL,
       F.DT_NASCIMENTO,
       D.ID_DEPENDENTE NUMERO_DEPENDENTE,
       D.NM_DEPENDENTE,
       D.DT_NASCIMENTO
FROM   T_SIP_FUNCIONARIO F LEFT JOIN T_SIP_DEPENDENTE D
ON     (F.CD_FUNC = D.CD_FUNC);

--
SELECT F.CD_FUNC,
       F.NM_FUNCIONARIO,
       F.DS_ESTADO_CIVIL,
       F.DT_NASCIMENTO,
       D.ID_DEPENDENTE NUMERO_DEPENDENTE,
       D.NM_DEPENDENTE,
       D.DT_NASCIMENTO
FROM   T_SIP_FUNCIONARIO F RIGHT JOIN T_SIP_DEPENDENTE D
ON     (F.CD_FUNC = D.CD_FUNC);

--
SELECT F.CD_FUNC,
       F.NM_FUNCIONARIO,
       F.DS_ESTADO_CIVIL,
       F.DT_NASCIMENTO,
       D.ID_DEPENDENTE NUMERO_DEPENDENTE,
       D.NM_DEPENDENTE,
       D.DT_NASCIMENTO
FROM   T_SIP_FUNCIONARIO F LEFT JOIN T_SIP_DEPENDENTE D
ON     (F.CD_FUNC = D.CD_FUNC)
WHERE D.CD_FUNC IS NULL;

--
SELECT F.CD_FUNC,
       F.NM_FUNCIONARIO,
       F.DS_ESTADO_CIVIL,
       F.DT_NASCIMENTO,
       D.ID_DEPENDENTE NUMERO_DEPENDENTE,
       D.NM_DEPENDENTE,
       D.DT_NASCIMENTO
FROM   T_SIP_FUNCIONARIO F RIGHT JOIN T_SIP_DEPENDENTE D
ON     (F.CD_FUNC = D.CD_FUNC)
WHERE F.CD_FUNC IS NULL;

--
