--01
SELECT * FROM T_SIP_FUNCIONARIO;

--02
SELECT T_SIP_FUNCIONARIO.CD_FUNC,
       T_SIP_FUNCIONARIO.CD_DEPTO,
       T_SIP_FUNCIONARIO.NM_FUNCIONARIO,
       T_SIP_FUNCIONARIO.DT_NASCIMENTO,
       T_SIP_FUNCIONARIO.DS_ESTADO_CIVIL,
       T_SIP_FUNCIONARIO.VL_SALARIO,
       T_SIP_FUNCIONARIO.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO;

--03
SELECT F.CD_FUNC,
       F.CD_DEPTO,
       F.NM_FUNCIONARIO,
       F.DT_NASCIMENTO,
       F.DS_ESTADO_CIVIL,
       F.VL_SALARIO,
       F.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO F;

--04
SELECT CD_FUNC,
       CD_DEPTO,
       NM_FUNCIONARIO,
       DT_NASCIMENTO,
       DS_ESTADO_CIVIL,
       VL_SALARIO,
       DT_ADMISSAO
FROM T_SIP_FUNCIONARIO;

--05
SELECT F.CD_FUNC,
       F.CD_DEPTO,
       F.NM_FUNCIONARIO,
       F.DT_NASCIMENTO,
       F.DS_ESTADO_CIVIL,
       F.VL_SALARIO,
       F.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO F
WHERE F.CD_DEPTO = 6;

--06
SELECT DISTINCT F.CD_DEPTO
FROM T_SIP_FUNCIONARIO F;

SELECT UNIQUE F.CD_DEPTO
FROM T_SIP_FUNCIONARIO F;

--07
--OP. +,-,*,/
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.VL_SALARIO * 1.20 AS VL_SALARIO_BONUS
FROM T_SIP_FUNCIONARIO F;

--08
SELECT F.CD_FUNC, 
       F.NM_FUNCIONARIO, 
       F.VL_SALARIO AS "VALOR DO SALÁRIO", 
       (F.VL_SALARIO * 12) + 1000 AS VL_SALARIO_ANUAL
FROM T_SIP_FUNCIONARIO F;

--09
SELECT D.CD_DEPTO, D.NM_DEPTO, D.SG_DEPTO
    FROM T_SIP_DEPTO D
    ORDER BY D.CD_DEPTO;
    
--10
SELECT D.CD_DEPTO, D.NM_DEPTO, D.SG_DEPTO
    FROM T_SIP_DEPTO D
    ORDER BY D.CD_DEPTO DESC;
    
--11
SELECT D.CD_DEPTO, D.NM_DEPTO, D.SG_DEPTO
    FROM T_SIP_DEPTO D
    ORDER BY D.NM_DEPTO;
    
--12
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO
    FROM T_SIP_FUNCIONARIO F
    ORDER BY F.VL_SALARIO DESC;
    
--13
SELECT F.CD_DEPTO, F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO
    FROM T_SIP_FUNCIONARIO F
    --WHERE F.CD_DEPTO != 1
    --WHERE F.CD_DEPTO <> 1
    WHERE F.CD_DEPTO > 1
    ORDER BY F.VL_SALARIO DESC;
    
--14
SELECT F.CD_DEPTO, F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO
    FROM T_SIP_FUNCIONARIO F
    WHERE F.CD_DEPTO > 1
    ORDER BY 1 ASC, 3 DESC, 4;
    
--15
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO 
FROM T_SIP_FUNCIONARIO F
WHERE F.VL_SALARIO >= 3000;

--16
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO 
FROM T_SIP_FUNCIONARIO F
--WHERE F.NM_FUNCIONARIO = 'Marina Silva';
WHERE F.CD_FUNC = 21;

--17
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO F
--WHERE F.NM_FUNCIONARIO = 'Marina Silva';
WHERE F.DT_ADMISSAO > '01-AUG-17';

--18
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO F
--WHERE F.NM_FUNCIONARIO = 'Marina Silva';
WHERE F.DT_ADMISSAO > TO_DATE('01/08/2017 22:31:20', 'DD/MM/YYYY HH24:MI:SS');

--19
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO F
--WHERE F.NM_FUNCIONARIO = 'Marina Silva';
WHERE F.DT_ADMISSAO >= TO_DATE('01/01/2017', 'DD/MM/YYYY')
AND F.DT_ADMISSAO <= TO_DATE('31/12/2017', 'DD/MM/YYYY');

--20
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO F
--WHERE F.NM_FUNCIONARIO = 'Marina Silva';
WHERE F.DT_ADMISSAO BETWEEN TO_DATE('01/01/2017', 'DD/MM/YYYY') 
AND TO_DATE('31/12/2017', 'DD/MM/YYYY');

--21
SELECT F.CD_DEPTO, F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO F
WHERE F.DT_ADMISSAO BETWEEN TO_DATE('01/01/2017', 'DD/MM/YYYY') 
AND TO_DATE('31/12/2017', 'DD/MM/YYYY')
OR F.CD_DEPTO = 1
ORDER BY 1;

--22
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO F
WHERE TO_CHAR(F.DT_ADMISSAO, 'YYYY') = ('2017');

--23 --IN
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO F
WHERE TO_CHAR(F.DT_ADMISSAO, 'YYYY') IN ('2017', '2017', '2018', '2019');

--24 --NOT IN
SELECT F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO F
WHERE TO_CHAR(F.DT_ADMISSAO, 'YYYY') NOT IN ('2017', '2017', '2018', '2019');

--25
SELECT F.CD_DEPTO, F.CD_FUNC, F.NM_FUNCIONARIO, F.VL_SALARIO, F.DT_ADMISSAO
FROM T_SIP_FUNCIONARIO F
WHERE F.DT_ADMISSAO NOT BETWEEN TO_DATE('01/01/2017', 'DD/MM/YYYY') 
AND TO_DATE('31/12/2017', 'DD/MM/YYYY');

--26
SELECT *
FROM T_SIP_FUNCIONARIO F
WHERE F.CD_DEPTO IN (1, 7, 4)
ORDER BY F.CD_DEPTO;

--27
SELECT *
FROM T_SIP_PROJETO P
WHERE P.DT_TERMINO IS NOT NULL;

--28
SELECT *
FROM T_SIP_PROJETO P
WHERE P.DT_TERMINO IS NULL;

--29
SELECT *
FROM T_SIP_DEPTO D
WHERE D.NM_DEPTO LIKE 'CO%';

--30
SELECT *
FROM T_SIP_DEPTO D
WHERE D.NM_DEPTO LIKE '_E%';

--31
SELECT *
FROM T_SIP_DEPTO D
WHERE D.NM_DEPTO LIKE 'E%';

--32
SELECT *
FROM T_SIP_DEPTO D
WHERE D.NM_DEPTO LIKE '%ME%';

--C:\AppData\Roaming\SQL Developer\mywork\